# Generated by Django 3.1.7 on 2022-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_mapspolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
