# Generated by Django 3.1.7 on 2022-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsline',
            old_name='fill_color',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='mapsline',
            name='stroke_color',
        ),
        migrations.AddField(
            model_name='mapsline',
            name='dash_array',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapsline',
            name='weight',
            field=models.FloatField(default=3),
        ),
    ]
