# Generated by Django 3.1.7 on 2022-03-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_admin', '0002_auto_20220324_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsline',
            name='line_cap',
            field=models.CharField(choices=[('butt', 'butt'), ('round', 'round'), ('square', 'square'), ('inherit', 'inherit')], default='round', max_length=255),
        ),
        migrations.AddField(
            model_name='mapsline',
            name='line_join',
            field=models.CharField(choices=[('miter', 'miter'), ('round', 'round'), ('bevel', 'bevel'), ('inherit', 'inherit')], default='round', max_length=255),
        ),
    ]
